[package]
name = "cc-test"
version = "0.1.0"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
edition = "2018"
publish = false

[lib]
name = "cc_test"
doctest = false
test = false

[build-dependencies]
cc = { path = "../.." }
which = "^8.0"

[features]
parallel = ["cc/parallel"]
test_cuda = []
